### ISSUE TITLE
Using the wrapper with Flutter

### ISSUE THREAD

**Issue by vmmc2** [google/codemirror.dart#114]
Is it possible to use this wrapper inside a Flutter application? If so, how could we do it?

**Comment by devoncarew** [comment]
You'd create a fluter web plugin, and that plugin would use this package directly.

**Comment by vmmc2** [comment]
Ok, understood. But I've never written a plugin before. Do you know any good tutorials about this subject?

**Comment by devoncarew** [comment]
There are some docs here: https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin, and for web plugins specifically, here: https://medium.com/flutter/how-to-write-a-flutter-web-plugin-5e26c689ea1.

**Comment by vmmc2** [comment]
I will take a look at both. Thank you for your time and patience.

**Comment by devoncarew** [comment]
Sure! We considered using a wrapper for https://github.com/flutter/devtools (we're re-writing it in Flutter web), but only need a read-only view, not editing, so are just implementing a code view in Flutter. That's a much simpler problem than editing :)

**Comment by domesticmouse** [comment]
@devoncarew please let me know if y’all open to breaking out parts of DartTools as separate widgets. I have some serious use cases for code viewer widget😏

**Comment by vmmc2** [comment]
@domesticmouse just for curiosity: have you ever tried this thing of doing a codemirror plugin for a flutter application?

**Comment by domesticmouse** [comment]
Hey @vmmc2, apologies I haven’t played with flutter web plugins yet. It’s on my todo list. Feel free to raise a bug on this repo and I’ll self assign it 😇

**Comment by vmmc2** [comment]
Oh.. Okay. Gonna probably start working on the codemirror web plugin tomorrow. If I face any bugs or issues I'll post here.

**Comment by domesticmouse** [comment]
I'm closing this out for now. If you have any further questions/requests, please feel free to open new bugs. Thanks!
