### ISSUE TITLE
Run the example dart file

### ISSUE THREAD

**Issue by abhimahatu123** [google/codemirror.dart#126]
Hey. I was checking out the `simple.dart` in the [example/](https://github.com/google/codemirror.dart/tree/master/example) folder.
How do I run it? My plan is integrate this in an Flutter app.

**Comment by domesticmouse** [comment]
A full example showing usage of CodeMirror is in https://github.com/dart-lang/dart-services/tree/master/example

Integrating with Flutter Web would be a very interesting sample. Please let us know how you get on with the integration!
