### ISSUE TITLE
examples of flutter

### ISSUE THREAD

**Issue by peter100u** [google/codemirror.dart#144]
Can you provide some examples of flutter

**Comment by peter100u** [comment]
Can you provide some examples of flutter mobile app

**Comment by domesticmouse** [comment]
@peter100u please take a look at https://flutter.dev/showcase

**Comment by peter100u** [comment]
Sorry, I didn't express it clearly. What I want is codemirror DART's flitter example, not the flitter example
https://github.com/google/codemirror.dart/pull/147#issuecomment-1007108105

**Comment by domesticmouse** [comment]
Dart is a programming language that can target servers with Dart VM, the web through dart2js, and Flutter. I'm not quite sure what you are looking for
