### ISSUE TITLE
Pub.dev lists `codemirror.dart` as Flutter SDK

### ISSUE THREAD

**Issue by paulohecht** [google/codemirror.dart#161]
This package makes codemirror available only through dart2js and currently can't be added to a flutter application without creating a low level plugin.

The listing in pub.dev is quite misleading in that regard, as it induces flutter developers to mistakenly assume that it's a flutter package. It can take quite a frustrating amount of time and energy to put the pieces together and finally comprehend that this package only supports web through dart2js.

<img width="1291" alt="image" src="https://user-images.githubusercontent.com/1753228/233515774-e5bb54e8-30c2-4f98-8220-8da87375b28d.png">

If there's no way to specify it's not a flutter package, there could be a mention to this at the top of the readme.

**Comment by peter100u** [comment]
It is better to support the Flutter platform than to update the documentation, after all, there are too few code editors in the Flutter ecosystem

**Comment by domesticmouse** [comment]
> It is better to support the Flutter platform than to update the documentation, after all, there are too few code editors in the Flutter ecosystem

Amusingly, apart from requiring a complete rewrite, making this package support Flutter would make it useless for the core reason I maintain this package - being the editor in DartPad.dev.
