### ISSUE TITLE
Codemirror conflicts with the polymer transformer

### ISSUE THREAD

**Issue by fedy2** [google/codemirror.dart#6]
When I add polymer dependency and transformer to my project, codemirror stop working and 404 errors appears in the console:

Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/css/codemirror.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/3024-day.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/3024-night.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/ambiance-mobile.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/ambiance.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/base16-dark.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/base16-light.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/blackboard.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/cobalt.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/eclipse.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/elegant.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/erlang-dark.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/lesser-dark.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/mbo.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/mdn-like.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/midnight.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/monokai.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/neat.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/neo.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/night.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/paraiso-dark.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/paraiso-light.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/pastel-on-dark.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/rubyblue.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/solarized.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/the-matrix.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/tomorrow-night-eighties.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/twilight.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/vibrant-ink.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/xq-dark.css
Failed to load resource: the server responded with a status of 404 (Not Found)
  http://localhost:8080/theme/xq-light.css

A sample project with the specified error can be found here: https://github.com/fedy2/codemirror_sample

**Comment by radicaled** [comment]
This workaround doesn't work if you use CodeMirror inside a Polymer element. The `<style />` tag ends up being empty after Polymer's transformer gets done with it.

This is what I had to do to get it working:

```html
<style>
 @import 'packages/codemirror/codemirror.css';
</style>
```

Note: using the latest Polymer (0.12), so I'm not sure if the problem I faced or this solution is applicable to earlier versions.

**Comment by devoncarew** [comment]
It looks like the explicitly import the codemirror css here as well: https://github.com/PolymerLabs/code-mirror).

I'd accept PR's updating the main readme.md w/ this info :)

**Comment by devoncarew** [comment]
Probably not going to take action on this.
