### ISSUE TITLE
`Span` overloads `operator==` but not `hashCode`

### ISSUE THREAD

**Issue by just95** [google/codemirror.dart#65]
The `Span` class overloads the equality operator. The documentation of `Object.operator==` states that:

> If a subclass overrides the equality operator it should override the hashCode method as well to maintain consistency.

But there is no `Span.hashCode` method. 

In Java I would probably write something like:
```dart      
int get hashCode {
  int prime = 31;
  int result = 1;
  result = prime * result + head.hashCode;
  result = prime * result + anchor.hashCode;
  return result;
}
```
However, I'm not exactly sure how well this will perform in Dart, especially when compiled to JavaScript.

The best alternative I know of is the `hash2` function from the `quiver` package.
This is what I'd usually use. I just wonder whether it is worth adding a dependency.

**Comment by devoncarew** [comment]
It makes sense to add a `hashCode` to Span. I would also be leery of adding a dep on quiver just for this use. The above code looks good; you could also do something like `int get hashCode => head.hashCode ^ anchor.hashCode`.

**Comment by just95** [comment]
Thanks for your feedback.
The XOR solution look very good to me and should be sufficient for this purpose.
I think I will do just that.
