### ISSUE TITLE
'JSObjectImpl' is not a subtype of type 'JsObject'

### ISSUE THREAD

**Issue by johnpryan** [google/codemirror.dart#74]
Codemirror started throwing this error, and we can't figure out the cause:

```
'JSObjectImpl' is not a subtype of type 'JsObject'
```

The usage was within an angular2 app:

```dart
    var element = (elementRef.nativeElement as Element);
    var container = element.querySelector('#container');
    var options = {
      "mode": "javascript",
      "theme": "default",
      "lineNumbers": "true"
    };
    editor = new CodeMirror.fromElement(container, options: options);
```

Changing to this solved the issue:

```dart
    var options = {
      "mode": "javascript",
      "theme": "default",
      "lineNumbers": "true"
    };
    var element = (elementRef.nativeElement as Element);
    var container = element.querySelector('#container');

    editor = new CodeMirror.fromElement(container, options: options);
    var doc =
        new Doc.fromProxy(new JsObject.fromBrowserObject(editor('getDoc')));
```

It seems like the result of `editor('getDoc')` was returning a JsObjectImpl.  I was unable to reproduce using the `example/` folder

**Comment by devoncarew** [comment]
Is `JSObjectImpl` not a subclass of `JsObject`? Is this a dart:js vs package:js thing?

**Comment by devoncarew** [comment]
There are definitely problems mixing streams there. @jacob314 would know more (though, he'd probably just say to try to avoid doing it).

**Comment by jacob314** [comment]
package:js and dart:js can't be mixed together. Using new JsObject.fromBrowserObject to force a dart:js wrapper instead of the raw JS object is a reaosnable workaround if you don't have time to switch all code to package:js

**Comment by johnpryan** [comment]
@jacob314 just to clarify; are you saying that any package that uses package:js (or uses any package that uses package:js) can't use dart:js (or any package that uses dart:js)?

**Comment by jacob314** [comment]
You can use both in the same app but you need to make sure you aren't directly passing objects created with dart:js to a library expecting package:js or vice versa.
Also, make sure you are not calling functions wrapped with the package:js allowInterop method to methods that later call them using dart:js

**Comment by johnpryan** [comment]
After more investigation, this is an angular2 issue.  Any component with children using a combination of `dart:js` and `package:js` will break.

To reproduce:

1. create an angular2 app with a component `parent_component`
2 create a child component that uses `dart:js`
3. create a child component that uses `package:js`
4. observe `dart:js` child component returns `JsObjectImpl` that is not a subtype of `JsObject`

This might have something to do with the way the angular2 transformer combines compnents

**Comment by johnpryan** [comment]
angular2 ticket: https://github.com/dart-lang/angular/issues/583
